lessons = {
    "бекл": ["Backend розробка (лекція)", "https://meet.google.com/ntv-xafm-imh"],
    "бекп1": ["Backend розробка (1 підгрупа, практика)", "https://meet.google.com/nic-ppxx-iif"],
    "бекп2": ["Backend розробка (2 підгрупа, практика)", "https://meet.google.com/wby-ccff-xgs"],
    "вебл": ["Web development (лекція)", "meet.google.com/cat-tnso-ydp"],
    "вебп1": ["Web development (1 підгрупа, практика)", "meet.google.com/cat-tnso-ydp"],
    "вебп2": ["Web development (2 підгрупа, практика)", "meet.google.com/cat-tnso-ydp"],
    "англ1": ["Англійська мова (1 підгрупа)", "https://meet.google.com/ygy-phic-sia"],
    "англ2": ["Англійська мова (2 підгрупа)", "https://us04web.zoom.us/j/3043052455?pwd=cVVnRnZuenhCNkFTck5oMldZN3AzZz09"],
    "рубіл": ["Мова програмування Ruby (лекція)", "https://meet.google.com/ntv-xafm-imh"],
    "рубіп1": ["Мова програмування Ruby (1 підгрупа, практика)", "https://meet.google.com/wby-ccff-xgs"],
    "рубіп2": ["Мова програмування Ruby (2 підгрупа, практика)", "https://meet.google.com/tyb-ipag-wih"],
    "інтерфл": ["Розробка адаптивних web-інтерфейсів (лекція)", "https://meet.google.com/frx-geko-fkw"],
    "інтерфп1": ["Розробка адаптивних web-інтерфейсів (1 підгрупа, практика)", "https://meet.google.com/tmt-hkcg-gwr"],
    "інтерфп2": ["Розробка адаптивних web-інтерфейсів (2 підгрупа, практика)", "https://meet.google.com/hbi-zydn-sii"],
    "арт": ["Арт-терапія (лекція)", "https://us04web.zoom.us/j/77078642601?pwd=pfZ61KmuWfhJvII0dfjdAPI8WoBxiy.1 "],
    "арт1": ["Арт-терапія (1 підгрупа, практика)", "https://us04web.zoom.us/j/79779287213?pwd=jjAEsWgXZXFYXcOqe9hCDMMZa27b9c.1 (код доступу: 2022)"],
    "арт2": ["Арт-терапія (2 підгрупа, практика)", "https://us04web.zoom.us/j/79779287213?pwd=jjAEsWgXZXFYXcOqe9hCDMMZa27b9c.1 (код доступу: 2022)"],
    "арт3": ["Арт-терапія (3 підгрупа, практика)", "https://us04web.zoom.us/j/79779287213?pwd=jjAEsWgXZXFYXcOqe9hCDMMZa27b9c.1 (код доступу: 2022)"],
    "пол": ["Польська мова", "https://us05web.zoom.us/j/4262746278?pwd=ZUNmbWx3VS93M3p3RUtzSEtmTFpPdz09"]
}
