from lessons import lessons

scheduleList = [
    [
        [
            [
                lessons["алгп"]
            ],
            [
                lessons["ткпп"]
            ],
            [
                lessons["веб"]
            ]
        ],
        [],
        [
            [
                lessons["ткпл"]
            ],
            [
                lessons["алгл"]
            ],
            [
                lessons["ооп"]
            ]
        ],
        [
            [
                lessons["кгозп"]
            ],
            [
                lessons["веб"]
            ],
            [
                lessons["нп"]
            ]
        ],
        [
            [
                lessons["ооп"]
            ],
            [
                lessons["англ"]
            ],
            [
                lessons["ткпп"]
            ],
            [
                lessons["фв"]
            ]
        ],
        [],
        []
    ],
    [
        [
            [
                lessons["алгп"]
            ],
            [
                lessons["тймсп"]
            ],
            [
                lessons["веб"]
            ]
        ],
        [],
        [
            [
                lessons["тймсл"]
            ],
            [
                lessons["алгл"]
            ],
            [
                lessons["ооп"]
            ]
        ],
        [
            [],
            [
                lessons["кгозл"]
            ],
            [
                lessons["нп"]
            ],
            [
                lessons["нп"]
            ]
        ],
        [
            [
                lessons["ооп"]
            ],
            [
                lessons["англ"]
            ],
            [
                lessons["ткпп"]
            ],
            [
                lessons["фв"]
            ]
        ],
        [],
        []
    ]
]