from lessons import lessons

scheduleList = [
    [
        [
            [
                lessons["ос"]
            ],
            [
                lessons["ооп"]
            ],
            [
                lessons["пай"]
            ],
            [
                lessons["чм"]
            ]
        ],
        [
            [
                lessons["пай"]
            ],
            [
                lessons["чм"]
            ],
            [
                lessons["англ"]
            ]
        ],
        [
            [
                lessons["пхп"]
            ],
            [
                lessons["обд"]
            ],
            [
                lessons["ос"]
            ]
        ],
        [],
        [
            [
                lessons["ооп"]
            ],
            [
                lessons["емпі"]
            ]
        ],
        [],
        []
    ],
    [
        [
            [
                lessons["обд"]
            ],
            [
                lessons["ооп"]
            ],
            [
                lessons["пхп"]
            ],
            [
                lessons["емпі"]
            ]
        ],
        [
            [
                lessons["пай"]
            ],
            [
                lessons["чм"]
            ],
            [
                lessons["англ"]
            ]
        ],
        [
            [
                lessons["пхп"]
            ],
            [
                lessons["обд"]
            ],
            [
                lessons["ос"]
            ]
        ],
        [],
        [
            [
                lessons["ооп"]
            ],
            [
                lessons["емпі"]
            ]
        ],
        [],
        []
    ]
]
